# Generated by Django 5.1.7 on 2025-05-04 14:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.URLField(blank=True)),
                ('spell_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('school', models.CharField(choices=[('Evocation', 'Evocation'), ('Necromancy', 'Necromancy'), ('Abjuration', 'Abjuration'), ('Conjuration', 'Conjuration'), ('Divination', 'Divination'), ('Enchantment', 'Enchantment'), ('Illusion', 'Illusion'), ('Transmutation', 'Transmutation')], max_length=30)),
                ('classes', models.JSONField(default=list, help_text='Örnek: ["Wizard","Sorcerer"]')),
                ('casting_time', models.CharField(max_length=30)),
                ('range', models.CharField(max_length=30)),
                ('components', models.JSONField(default=dict, help_text='{"verbal": true, "somatic": true, "material": false}')),
                ('material_detail', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('concentration', models.BooleanField(default=False)),
                ('ritual', models.BooleanField(default=False)),
                ('effect', models.JSONField(default=dict, help_text="Şema örn: {'type':'damage','dice':{'num':2,'size':8,'modifier':3},'target':'enemy','damage_type':'fire','area':{'shape':'sphere','radius':20},'save':{'ability':'Dex','on_success':'half'}}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
