# Generated by Django 5.1.7 on 2025-05-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='effect',
            field=models.JSONField(default=dict, help_text="Örnek şema: {'type':'damage','dice':{'num':2,'size':8,'modifier':3},'target':'enemy','damage_type':'fire','area':{'shape':'sphere','radius':20},'save':{'ability':'Dex','on_success':'half'}}"),
        ),
        migrations.AlterField(
            model_name='spell',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='spell_icons/'),
        ),
    ]
