# Generated by Django 5.1.7 on 2025-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_alter_spell_effect_alter_spell_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='effect',
        ),
        migrations.AddField(
            model_name='spell',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('fire', 'Ateş'), ('glacier', 'Buz'), ('poison', 'Zehir'), ('lightning', 'Yıldırım'), ('earth', 'Toprak'), ('power', 'Arcane (Güç)'), ('sonic', 'Sonic')], help_text='Hasar büyüsü için hasar tipi', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='dice_modifier',
            field=models.IntegerField(default=0, help_text='Zar atma sonrası eklenecek modifikasyon (modifier)'),
        ),
        migrations.AddField(
            model_name='spell',
            name='dice_num',
            field=models.PositiveSmallIntegerField(default=1, help_text='Atılacak zar sayısı (num)'),
        ),
        migrations.AddField(
            model_name='spell',
            name='dice_size',
            field=models.PositiveSmallIntegerField(default=6, help_text='Zar yüz sayısı (size)'),
        ),
        migrations.AddField(
            model_name='spell',
            name='effect_type',
            field=models.CharField(choices=[('damage', 'Hasar'), ('heal', 'İyileştirme'), ('buff', 'Güçlendirme'), ('debuff', 'Zayıflatma')], default='damage', help_text='Büyünün etki türü', max_length=10),
        ),
        migrations.AddField(
            model_name='spell',
            name='scope',
            field=models.CharField(choices=[('single', 'Tek Hedef'), ('area', 'Alan Etkili'), ('self', 'Kendine')], default='single', help_text='Büyünün hedef kapsamı', max_length=10),
        ),
    ]
