# Generated by Django 5.1.7 on 2025-03-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invited_lobby_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lobby_invite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
