# Generated by Django 5.1.7 on 2025-05-06 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spells', '0002_alter_spell_effect_alter_spell_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='creatures/icons/')),
                ('hit_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('challenge_rating', models.FloatField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('melee_attack_dice', models.CharField(blank=True, help_text="e.g. '2d6+3'", max_length=20, null=True)),
                ('ranged_attack_dice', models.CharField(blank=True, help_text="e.g. '1d8+2'", max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('spells', models.ManyToManyField(blank=True, related_name='creatures', to='spells.spell')),
            ],
        ),
    ]
