# Generated by Django 5.1.7 on 2025-05-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0003_alter_creature_challenge_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='grid_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='grid_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='initiative_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
