# Generated by Django 5.1.7 on 2025-05-05 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spells', '0002_alter_spell_effect_alter_spell_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='item_icons/')),
                ('item_type', models.CharField(choices=[('Weapon', 'Weapon'), ('Armor', 'Armor'), ('Consumable', 'Consumable'), ('Misc', 'Misc')], max_length=20)),
                ('subtype', models.CharField(choices=[('CLUB', 'Club'), ('DAGGER', 'Dagger'), ('HAND_AXE', 'Hand Axe'), ('MACE', 'Mace'), ('STAFF', 'Staff'), ('SPEAR', 'Spear'), ('BATTLE_AXE', 'Battle Axe'), ('GREAT_AXE', 'Great Axe'), ('GREATSWORD', 'Greatsword'), ('HALBERD', 'Halberd'), ('LONGSWORD', 'Longsword'), ('SHORT_SWORD', 'Short Sword'), ('WARHAMMER', 'Warhammer'), ('CROSSBOW', 'Crossbow'), ('HAND_CROSSBOW', 'Hand Crossbow'), ('HEAVY_CROSSBOW', 'Heavy Crossbow'), ('BOW', 'Bow'), ('SHORT_BOW', 'Short Bow'), ('LONG_BOW', 'Long Bow'), ('GREAT_BOW', 'Great Bow'), ('SHIELD', 'Shield'), ('POTION', 'Potion'), ('SCROLL', 'Scroll'), ('MISC', 'Misc')], default='MISC', max_length=20)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Legendary', 'Legendary')], default='Common', max_length=20)),
                ('value', models.PositiveIntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('properties', models.JSONField(default=dict, help_text='Item-specific stats/effects')),
                ('bonuses', models.JSONField(default=list, help_text='List of bonus effects')),
                ('damage_dice', models.CharField(blank=True, help_text="e.g. '2d6'", max_length=10)),
                ('damage_modifier', models.IntegerField(default=0, help_text='Numeric damage modifier')),
                ('ac_bonus', models.IntegerField(default=0, help_text='Armor Class bonus')),
                ('equip_slot', models.CharField(choices=[('HEAD', 'Head'), ('CHEST', 'Chest'), ('PANT', 'Pant'), ('BOOT', 'Boot'), ('NECKLACE', 'Necklace'), ('EARRING', 'Earring'), ('RING', 'Ring'), ('MAIN_HAND', 'Main Hand'), ('OFF_HAND', 'Off Hand'), ('INVENTORY', 'Inventory')], default='INVENTORY', max_length=20)),
                ('two_handed', models.BooleanField(default=False, help_text='Occupies both hands if true')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('spells', models.ManyToManyField(blank=True, help_text='Spells granted when equipped', related_name='items', to='spells.spell')),
            ],
        ),
    ]
