# Generated by Django 5.1.7 on 2025-05-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ac_bonus',
            field=models.IntegerField(blank=True, default=0, help_text='Armor Class bonus', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='bonuses',
            field=models.JSONField(blank=True, default=list, help_text='List of bonus effects', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage_dice',
            field=models.CharField(blank=True, help_text="e.g. '2d6'", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage_modifier',
            field=models.IntegerField(blank=True, default=0, help_text='Numeric damage modifier', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='equip_slot',
            field=models.CharField(blank=True, choices=[('HEAD', 'Head'), ('CHEST', 'Chest'), ('PANT', 'Pant'), ('BOOT', 'Boot'), ('NECKLACE', 'Necklace'), ('EARRING', 'Earring'), ('RING', 'Ring'), ('MAIN_HAND', 'Main Hand'), ('OFF_HAND', 'Off Hand'), ('INVENTORY', 'Inventory')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Item-specific stats/effects', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='subtype',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='two_handed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
