# Generated by Django 5.1.7 on 2025-07-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_ac_bonus_alter_item_bonuses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='equip_slot',
            field=models.CharField(blank=True, choices=[('HEAD', 'Head'), ('CHEST', 'Chest'), ('PANT', 'Pant'), ('BOOT', 'Boot'), ('NECKLACE', 'Necklace'), ('EARRING', 'Earring'), ('RING', 'Ring'), ('MELEE_WEAPON', 'Melee Weapon'), ('RANGED_WEAPON', 'Ranged Weapon'), ('OFF_HAND', 'Off Hand'), ('INVENTORY', 'Inventory')], max_length=20, null=True),
        ),
    ]
