# Generated by Django 5.1.7 on 2025-03-09 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'character_classes',
            },
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('lobby_id', models.AutoField(db_column='lobby_id', primary_key=True, serialize=False)),
                ('lobby_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lobbies',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('traits', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'races',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('lobby_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('gold', models.IntegerField(default=10)),
                ('equipment', models.JSONField(blank=True, default=dict)),
                ('prepared_spells', models.JSONField(blank=True, default=dict)),
                ('class_features', models.JSONField(blank=True, default=dict)),
                ('character_class', models.ForeignKey(blank=True, db_column='class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.class')),
                ('race', models.ForeignKey(blank=True, db_column='race', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.race')),
            ],
            options={
                'db_table': 'characters',
            },
        ),
    ]
