# Generated by Django 5.1.7 on 2025-05-06 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_alter_item_ac_bonus_alter_item_bonuses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(db_column='class', max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('equipment', models.JSONField(blank=True, default=dict)),
                ('spells', models.JSONField(blank=True, default=dict)),
                ('gold', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'character_templates',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'character_classes',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('traits', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'races',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('lobby_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=10)),
                ('xp', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('gold', models.IntegerField(default=10)),
                ('inventory', models.JSONField(blank=True, default=list)),
                ('prepared_spells', models.JSONField(blank=True, default=dict)),
                ('class_features', models.JSONField(blank=True, default=dict)),
                ('background', models.CharField(blank=True, max_length=100, null=True)),
                ('personality_traits', models.TextField(blank=True, null=True)),
                ('ideals', models.TextField(blank=True, null=True)),
                ('bonds', models.TextField(blank=True, null=True)),
                ('flaws', models.TextField(blank=True, null=True)),
                ('chest_armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('ear1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('ear2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('hand_armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('head_armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('legs_armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('main_hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('necklace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('off_hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('ring1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('ring2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('character_class', models.ForeignKey(blank=True, db_column='class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.class')),
                ('race', models.ForeignKey(blank=True, db_column='race', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.race')),
            ],
            options={
                'db_table': 'characters',
            },
        ),
    ]
