# Generated by Django 5.1.7 on 2025-05-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ac',
            field=models.IntegerField(default=0),
        ),
    ]
