# Generated by Django 5.1.7 on 2025-05-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_character_ac'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='action_points',
            field=models.IntegerField(default=1),
        ),
    ]
