# Generated by Django 5.1.7 on 2025-05-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_character_action_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='icon',
            field=models.ImageField(blank=True, help_text='PNG or JPG image for character icon (64×64 recommended)', null=True, upload_to='character_icons/'),
        ),
        migrations.AddField(
            model_name='character',
            name='max_hp',
            field=models.IntegerField(default=10),
        ),
    ]
