# Generated by Django 5.1.7 on 2025-05-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_character_icon_character_max_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='melee_dice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='ranged_dice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
