# Generated by Django 5.1.7 on 2025-07-17 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_character_damage_dealt_character_damage_taken_and_more'),
        ('items', '0003_alter_item_equip_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='main_hand',
            new_name='melee_weapon',
        ),
        migrations.AddField(
            model_name='character',
            name='ranged_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item'),
        ),
    ]
