# spells/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import SpellViewSet
from .views import (
    # 1-10
    MagicMissileSpellView,
    FireballSpellView,
    LightningBoltSpellView,
    HealingWordSpellView,
    ShieldSpellView,
    InvisibilitySpellView,
    SleepSpellView,
    AcidArrowSpellView,
    MagicWeaponSpellView,
    FlySpellView,
    # 11-20
    ConeOfColdSpellView,
    DominatePersonSpellView,
    DisintegrateSpellView,
    EarthquakeSpellView,
    HoldPersonSpellView,
    LightningStormSpellView,
    PolymorphSpellView,
    SunbeamSpellView,
    WallOfFireSpellView,
    TimeStopSpellView,
    # 21-30
    BlightSpellView,
    CharmPersonSpellView,
    DarknessSpellView,
    HasteSpellView,
    SlowSpellView,
    CounterspellSpellView,
    FireShieldSpellView,
    IceStormSpellView,
    PrismaticSpraySpellView,
    DispelMagicSpellView,
    # 31-40
    AnimateDeadSpellView,
    BanishmentSpellView,
    CircleOfDeathSpellView,
    CloudkillSpellView,
    ConfusionSpellView,
    DelayedBlastFireballSpellView,
    DimensionDoorSpellView,
    DominateMonsterSpellView,
    FeeblemindSpellView,
    TrueResurrectionSpellView,
    # 41-50
    ForcecageSpellView,
    TelekinesisSpellView,
    EarthbindSpellView,
    MindBlankSpellView,
    MazeSpellView,
    PowerWordKillSpellView,
    FingerOfDeathSpellView,
    GlobeOfInvulnerabilitySpellView,
    OttosIrresistibleDanceSpellView,
    SymbolSpellView,
    # 51-60
    MassHealSpellView,
    ChainLightningSpellView,
    ReverseGravitySpellView,
    FleshToStoneSpellView,
    AnimateObjectsSpellView,
    AntimagicFieldSpellView,
    EyebiteSpellView,
    ControlWeatherSpellView,
    HolyAuraSpellView,
    WishSpellView,
)

router = routers.DefaultRouter()
router.register(r'spells', SpellViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('magic-missile/', MagicMissileSpellView.as_view(), name='magic-missile'),
    path('fireball/', FireballSpellView.as_view(), name='fireball'),
    path('lightning-bolt/', LightningBoltSpellView.as_view(), name='lightning-bolt'),
    path('healing-word/', HealingWordSpellView.as_view(), name='healing-word'),
    path('shield/', ShieldSpellView.as_view(), name='shield'),
    path('invisibility/', InvisibilitySpellView.as_view(), name='invisibility'),
    path('sleep/', SleepSpellView.as_view(), name='sleep'),
    path('acid-arrow/', AcidArrowSpellView.as_view(), name='acid-arrow'),
    path('magic-weapon/', MagicWeaponSpellView.as_view(), name='magic-weapon'),
    path('fly/', FlySpellView.as_view(), name='fly'),
    # 11-20
    path('cone-of-cold/', ConeOfColdSpellView.as_view(), name='cone-of-cold'),
    path('dominate-person/', DominatePersonSpellView.as_view(), name='dominate-person'),
    path('disintegrate/', DisintegrateSpellView.as_view(), name='disintegrate'),
    path('earthquake/', EarthquakeSpellView.as_view(), name='earthquake'),
    path('hold-person/', HoldPersonSpellView.as_view(), name='hold-person'),
    path('lightning-storm/', LightningStormSpellView.as_view(), name='lightning-storm'),
    path('polymorph/', PolymorphSpellView.as_view(), name='polymorph'),
    path('sunbeam/', SunbeamSpellView.as_view(), name='sunbeam'),
    path('wall-of-fire/', WallOfFireSpellView.as_view(), name='wall-of-fire'),
    path('time-stop/', TimeStopSpellView.as_view(), name='time-stop'),
    # 21-30
    path('blight/', BlightSpellView.as_view(), name='blight'),
    path('charm-person/', CharmPersonSpellView.as_view(), name='charm-person'),
    path('darkness/', DarknessSpellView.as_view(), name='darkness'),
    path('haste/', HasteSpellView.as_view(), name='haste'),
    path('slow/', SlowSpellView.as_view(), name='slow'),
    path('counterspell/', CounterspellSpellView.as_view(), name='counterspell'),
    path('fire-shield/', FireShieldSpellView.as_view(), name='fire-shield'),
    path('ice-storm/', IceStormSpellView.as_view(), name='ice-storm'),
    path('prismatic-spray/', PrismaticSpraySpellView.as_view(), name='prismatic-spray'),
    path('dispel-magic/', DispelMagicSpellView.as_view(), name='dispel-magic'),
    # 31-40
    path('animate-dead/', AnimateDeadSpellView.as_view(), name='animate-dead'),
    path('banishment/', BanishmentSpellView.as_view(), name='banishment'),
    path('circle-of-death/', CircleOfDeathSpellView.as_view(), name='circle-of-death'),
    path('cloudkill/', CloudkillSpellView.as_view(), name='cloudkill'),
    path('confusion/', ConfusionSpellView.as_view(), name='confusion'),
    path('delayed-blast-fireball/', DelayedBlastFireballSpellView.as_view(), name='delayed-blast-fireball'),
    path('dimension-door/', DimensionDoorSpellView.as_view(), name='dimension-door'),
    path('dominate-monster/', DominateMonsterSpellView.as_view(), name='dominate-monster'),
    path('feeblemind/', FeeblemindSpellView.as_view(), name='feeblemind'),
    path('true-resurrection/', TrueResurrectionSpellView.as_view(), name='true-resurrection'),
    # 41-50
    path('forcecage/', ForcecageSpellView.as_view(), name='forcecage'),
    path('telekinesis/', TelekinesisSpellView.as_view(), name='telekinesis'),
    path('earthbind/', EarthbindSpellView.as_view(), name='earthbind'),
    path('mind-blank/', MindBlankSpellView.as_view(), name='mind-blank'),
    path('maze/', MazeSpellView.as_view(), name='maze'),
    path('power-word-kill/', PowerWordKillSpellView.as_view(), name='power-word-kill'),
    path('finger-of-death/', FingerOfDeathSpellView.as_view(), name='finger-of-death'),
    path('globe-of-invulnerability/', GlobeOfInvulnerabilitySpellView.as_view(), name='globe-of-invulnerability'),
    path("ottos-irresistible-dance/", OttosIrresistibleDanceSpellView.as_view(), name="ottos-irresistible-dance"),
    path('symbol/', SymbolSpellView.as_view(), name='symbol'),
    # 51-60
    path('mass-heal/', MassHealSpellView.as_view(), name='mass-heal'),
    path('chain-lightning/', ChainLightningSpellView.as_view(), name='chain-lightning'),
    path('reverse-gravity/', ReverseGravitySpellView.as_view(), name='reverse-gravity'),
    path('flesh-to-stone/', FleshToStoneSpellView.as_view(), name='flesh-to-stone'),
    path('animate-objects/', AnimateObjectsSpellView.as_view(), name='animate-objects'),
    path('antimagic-field/', AntimagicFieldSpellView.as_view(), name='antimagic-field'),
    path('eyebite/', EyebiteSpellView.as_view(), name='eyebite'),
    path('control-weather/', ControlWeatherSpellView.as_view(), name='control-weather'),
    path('holy-aura/', HolyAuraSpellView.as_view(), name='holy-aura'),
    path('wish/', WishSpellView.as_view(), name='wish'),


]
